### ISSUE TITLE
Broken avatar if no gravatar email?

### ISSUE THREAD

**Issue by philippneugebauer** [glittergallery/GlitterGallery#248]
Took me some while to set up GlitterGallery due to Windows problems, so I switched now to Linux.

Anyway, after signing up with some fake data, I have a broken image in my profile.

When I looked into the code in the application helper and did some search about gravatars default behavior at not found emails, I can't really understand this problem.

Is that a local problem I encountered or can you reproduce that?

**Comment by Alwahsh** [comment]
This happens locally only because the default image is hosted locally while it has to be on the internet to appear. This just happens in development, not in production

**Comment by philippneugebauer** [comment]
Why is this picture not part of the git repository?

**Comment by Alwahsh** [comment]
It is a part of the git repository:
https://github.com/glittergallery/GlitterGallery/blob/master/public/happypanda.png
it's just that gravatar needs teh path of the image to be an online picture. Locally, the picture is at localhost:3000/happypanda.png which is not online. That's why you see nothing.

**Comment by EmilyDirsh** [comment]
We could change that configuration setting to use the github hosted image just for the dev environment, just need to add a check.

**Comment by mecyborg** [comment]
@EmilyDirsh Fixed with #257
